name: Release Please

on:
  push:
    branches:
      - main
      - development
      - staging

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.ADMIN_EMAIL}}
          git config --global user.name ${{ secrets.ADMIN_USER }}

      - name: Release to staging
        if: github.ref == 'refs/heads/staging'
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: app1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release to development
        if: github.ref == 'refs/heads/development'
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: lib1
          token: ${{ secrets.GITHUB_TOKEN }}
